# カラーテーマ
#[[plugins]]
#repo = 'Rigellute/rigel'
# hook_add = '''
#    set termguicolors
#    syntax enable
#    colorscheme rigel
#'''

# カラーテーマ
[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
    syntax enable
    colorscheme molokai
    let g:molokai_original = 1
    set t_Co=256
'''
